### ISSUE TITLE
Noob question about tests

### ISSUE THREAD

**Issue by k33g** [mklabs/tilt#7]
I update `index.jsx`

```
  index(req, res) {
    return res.render('index', { name: 'Bob!' });
  }
```

I change the tests:

```
    it('Renders homepage', (done) => {
      request(this.app.server)
        .get('/')
        .expect('Content-Type', 'text/html')
        .expect(/Hello Bob/)
        .end(done);
    });

```

but I still have this error:

```
 Test failed.  See above for more details.
  1) Tilt HTTP server with module based architecture Renders homepage:
     Error: expected body '<!doctype html><div>Hello Title!</div>' to match /Hello Bob/
```

What I forgot?

**Comment by mklabs** [comment]
Nothing.

**Comment by mklabs** [comment]
I think it's because of vertical vs horizontal.

Take care of updating the correct app, for modular -> horizontal. for HTTP server -> vertical.

**Comment by k33g** [comment]
I think I have not understand the notion of vertical and horizontal
are they independent ?
so they use the same test file ?

**Comment by mklabs** [comment]
Yes, they are two different applications.

Two examples to test two kind of file organization.

**Comment by mklabs** [comment]
Tests should probably be split in two files, I agree.
